### PR TITLE
Fix  Array bounds problem

### PR DESCRIPTION
**Pull request by ggaoming**
Fix Bug
 Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
 line 214 “ j < n”
 when j is bigger than n, the loop will not break sometimes. because the j value is beyond the int_max value.

### CODE REVIEW

**Comment by chiefx86** [comment]
Do you have an example for this?  I'm not sure I get why a cast from size_t to int is necessary, both variables have the same type.

**Comment by ggaoming** [comment]
i download version 1.0 from pypip
the input string is '冠状动脉粥样硬化性心脏病是冠状动脉血管发生动脉粥样硬化病变而引起血管腔狭窄或阻塞'  the key is [冠状动脉粥样硬化, 心脏病 , 动脉粥样硬化 ]the program will exit with  (interrupted by signal 11: SIGSEGV), the output is   冠状动脉粥样硬化 0 24;心脏病 27 36;动脉粥样硬化 63 81; 400; the last number 400 means the j reach 400 but the input string's length is 120.

**Comment by chiefx86** [comment]
I assume it is because you've grabbed it from pypip and this doesn't use this version. I'm not the original creator of this code, I just uploaded my 64 bit patch.

I've build the code and tried it with your example:

```
import ahocorasick
tree = ahocorasick.KeywordTree()
tree.add("冠状动脉粥样硬化")
tree.add("心脏病")
tree.add("动脉粥样硬化")
tree.make()
tree.search("冠状动脉粥样硬化性心脏病是冠状动脉血管发生动脉粥样硬化病变而引起血管腔狭窄或阻塞")
# (0, 24)
list(tree.findall("冠状动脉粥样硬化性心脏病是冠状动脉血管发生动脉粥样硬化病变而引起血管腔狭窄或阻塞"))
# [(0, 24), (27, 36), (63, 81)]
```

It did not crash. Can you verify that this also happens when you use the code from this repository?
If it is the case - does this happen all the time or just sometimes?

**Comment by ggaoming** [comment]
Sorry, this does  not happen in your code, i mistake you as the author，this happend in 1.0.

**Comment by chiefx86** [comment]
No worries

**Pull request closed without merging**
